### ISSUE TITLE
Built in logger

### ISSUE THREAD

**Issue by heybereket** [alii/mammot#10]
**Is your feature request related to a problem? Please describe.**
We don't have a built in logger currrently for developers to debug, which in some ways can be good as developers can use their own loggers, however we should also have one built in to make DX smooth.

**Describe the solution you'd like**
We can have a type definition for a few types of loggers, for example:
If we want, we can also add .logger before the type of logger.
```
Mammot.debug()
Mammot.info()
Mammot.event()
Mammot.error()
Mammot.warn()
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by anddddrew** [comment]
ref #16 I can close this now
