### ISSUE TITLE
chore: Implement basic CI

### ISSUE THREAD

**Issue by alii** [alii/mammot#6]
This should run ESLint, and the `tc` script in the root package JSON to check types across the project. It should run on pull requests and on pushes to `master`.

**Comment by favalonx** [comment]
Hey @alii, currently both of the tc and eslint tests fail for the **example/basic** project. Because the source code in this project uses `@mammot/core` which is not added in `package.json`.
When I exclude the **example** directory, everything passes.
What do I do about it?
